### PR TITLE
Preference modal duplicate

### LINKED ISSUE #26: Preference modal

### PR DESCRIPTION
**Pull request by milesba4**
Created a duplicate branch of preference modal and fixed all possible conflicts

### CODE REVIEW

**Review by gabremo — APPROVED** [review]
Looks awesome!

**Review by LifeBringer — CHANGES_REQUESTED** [review]
Remove console.log from commits

**Comment by milesba4** [comment]
Removed comments

**Comment by milesba4** [comment]
removed console.log statements

**Review by LifeBringer — APPROVED** [review]
LGTM, thanks for incorporating the feedback.

**Pull request merged**
